config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: %w[index new show create] do
    resources :doses, only: %w[new create]
  end
  delete 'doses/:id', to: 'doses#destroy', as: :destroy
  get 'gotcha', to: 'cocktails#gotcha'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  
  def index
    @cocktails = Cocktail.all
  end
  
  def gotcha; end
  
  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private
  
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # @ingredient = Ingredient.find(params['dose']['ingredient_id'])
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/gotcha.html.erb
<div
    class="bg-image d-flex justify-content-center align-items-center"
    style="
            background-image: url('https://res.cloudinary.com/dpiiypeop/image/upload/v1614957890/test/gotcha_2_ufliqe.png');
            height: 100vh;
            "
    >
  <h1 class="text-white"></h1>

</div>


<%# https://res.cloudinary.com/dpiiypeop/image/upload/v1614957890/test/gotcha_2_ufliqe.png %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://hhp-blog.s3.amazonaws.com/2018/08/iStock-611986658.jpg);">
  <div class="container">
    <h1>Mr Cocktail is here!</h1>
    <p>Just what the doctor ordered</p>
  </div>
</div>
<div class="container mb-4 d-flex justify-content-center w-100">
<div class="cards col-10 mt-3">
<%# <%= cl_image_tag("https://res.cloudinary.com/dpiiypeop/image/upload/c_thumb,w_200,g_face/v1614942832/khcw0cnrznginzjcgofe.jpg",
      width: 400, height: 300, crop: :fill) %>

<% @cocktails.each do |cocktail| %>
  <% if cocktail.photo.attached? %> 
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, crop: :fill %>')">
    <%= link_to cocktail.name, cocktail_path(cocktail), class: "btn btn-ghost" %>
  </div>
  <% else %> 
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://hhp-blog.s3.amazonaws.com/2018/08/iStock-611986658.jpg)">
    <%= link_to cocktail.name, cocktail_path(cocktail), class: "btn btn-ghost" %>
  </div>
  <% end %>
  <% end %>
</div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="form-card  py-4 px-3">
    <div class="form-card-content">
      <h1>Create your cocktail here!</h1>

      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-block btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container mt-5 d-flex cocktail-card">
  <div class ="card-image">
    <% if @cocktail.photo.attached? %> 
      <div class="show-card-category h-90" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, height: 600, crop: :fill %>')">
      </div>
    <% else %> 
      <div class="show-card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://hhp-blog.s3.amazonaws.com/2018/08/iStock-611986658.jpg)">
        <%= link_to @cocktail.name, cocktail_path(@cocktail), class: "btn btn-ghost" %>
      </div>
    <% end %>
  </div>
    <div class="show-card-info d-flex justify-content-between flex-column">
      <div class="ingredients">
          <h2><%= @cocktail.name %></h2>
        <% @cocktail.doses.each do |dose| %>
          <div class="d-flex">
            <div>
              <h4 class='ingredient-text'>
              <%= dose.description %> |  <%=dose.ingredient.name %>
              </h4>
            </div>
              <div>
                <%= link_to destroy_path(dose), method: :delete do %>
                  <i class="mt-2 ml-2 fas fa-trash-alt"></i>
                <% end %>
              </div>
          </div>
        <% end %>
      </div>
        <div class="d-flex-inline m-3">
          <%= link_to "Whats in this drink?",  new_cocktail_dose_path(@cocktail), class: "btn btn-sm btn-secondary mb-2  mt-2" %>
          <%= link_to "Back to drinks list",  cocktails_path, class: "btn btn-sm btn-secondary mb-2 mt-2" %>
        </div>
    </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<h1>What's in your cocktail?</h1>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon-e7ebb781e922290e24d010d0248a33a35e5dea980295afbc35978a40b135fc1f.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,100&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <%= image_tag "logo-8868a3f5f3bf9d32501d5799cb1f7c0727307a7b7ba3a565d4d1c211fc3a14bd.png" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active d-flex align-items-center">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item dropdown">
    
        <img class="avatar bg-dark dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src=<%= asset_path('avatar_me.jpg') %> />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/gotcha" target="_blank">Free Beer</a>
        </div>  
      </li>
      <li>
       <%= link_to "New cocktail", new_cocktail_path, class: "btn btn-primary ml-2" %>
      </li>
    </ul>
  </div>
</div>
  <div class="main-container">
      <%= yield %>
  </div>
    <div class="footer">
      <div class="footer-links text-center">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
      </div>
    </div>
  </body>
</html>